spring:
  banner:    location: classpath:banner/banner.txt
  datasource:    url: jdbc:mysql//localhost:3306/mydb
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update      naming:        physical-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect
server:  error:    whitelabel:      enabled: false